### ISSUE TITLE
Issues with the eww bar

### ISSUE THREAD

**Issue by suhaylmv** [Selmer443/dotfiles#10]
As you can see from the photo of the bar, some things are displayed incorrectly: the widget in the right of virtual desktops and an icon missing in the right of wifi. Also I would like to remove 5 widgets which are on the left of the clock, how can I do it?
![bugged eww bar](https://user-images.githubusercontent.com/64747225/222891265-605c3c3b-105d-4a1c-9a12-68b6df0a6354.png)

**Comment by Selmer443** [comment]
I see your issue, I will restructure some of the eww config so that it will be very easy for you to remove or add widgets as you'd like. I will also update the list of installed packages you have to include the fonts used for icons. For reference here are the two packages you can install from the AUR which should fix this: ttf-font-awesome and ttf-jetbrains-mono-nerd. I will post another comment here when I have restructured the eww config, this will allow you to comment out a few lines and then remove/add widgets as you like. Thanks for your feedback!

**Comment by suhaylmv** [comment]
Thanks for your effort and such a quick response!

**Comment by Selmer443** [comment]
hey I'm working on a neater solution, but for now you can go into .config/eww/fool_moon/bar/eww.yuck and comment out the widgets you dont want or remove them. here you can see I commented out a few under the right widget. Also keep in mind if you are interested in keeping your dotfiles managed with chezmoi you should be pulling changes from this github repo and then running chezmoi apply, while checking to see when chezmoi prompts you to override changes, you can choose to keep your own (skip), overwrite them (overwrite option), or open a diff to see the changes. You can read on chezmoi's documentation more in depth for info, also note the chezmoi re-add command which re-add all of the files back into chezmoi's directory and hence the git repository. you can use chezmoi cd to see where chezmoi is storing the files if you used chezmoi like in the readme.
![image](https://user-images.githubusercontent.com/93581805/222895600-9c198a3c-1d9e-4e92-90e5-7265c63020e5.png)

**Comment by suhaylmv** [comment]
It works, thanks. When I have time I'll dive into chezmoi's documentation
